### PR TITLE
Creating project folder and moving docs folder to inside it

### PR DESCRIPTION
**Pull request by Luccasoli**
As was requested in #14 

I created project folder and moved docs folder to inside it

Curiosity: i did everything through github.dev, i didn't even know i could edit the code too 🤣

### CODE REVIEW

**Comment by Luccasoli** [comment]
@omariosouto i think that you will need to change the docs-web root dir in vercel too 😕

**Comment by omariosouto** [comment]
Thank you @Luccasoli you are the first externa contributor! Do you allow me to show your contribution in one of my next videos?

**Comment by Luccasoli** [comment]
@omariosouto Yes! And I'll also try to collaborate on other issues, I think it's a great incentive for me to study packages and monorepository

**Comment by omariosouto** [comment]
I will create more issues, the next one I believe that is to have husky proctecting commits without conventional commit structures

**Pull request merged**
